cd Linear; convert -delay 2 -loop 0 *.png ../Linear.gif; cd ..
cd InQuad; convert -delay 2 -loop 0 *.png ../InQuad.gif; cd ..
cd OutQuad; convert -delay 2 -loop 0 *.png ../OutQuad.gif; cd ..
cd InOutQuad; convert -delay 2 -loop 0 *.png ../InOutQuad.gif; cd ..
cd InCubic; convert -delay 2 -loop 0 *.png ../InCubic.gif; cd ..
cd OutCubic; convert -delay 2 -loop 0 *.png ../OutCubic.gif; cd ..
cd InOutCubic; convert -delay 2 -loop 0 *.png ../InOutCubic.gif; cd ..
cd InQuart; convert -delay 2 -loop 0 *.png ../InQuart.gif; cd ..
cd OutQuart; convert -delay 2 -loop 0 *.png ../OutQuart.gif; cd ..
cd InOutQuart; convert -delay 2 -loop 0 *.png ../InOutQuart.gif; cd ..
cd InQuint; convert -delay 2 -loop 0 *.png ../InQuint.gif; cd ..
cd OutQuint; convert -delay 2 -loop 0 *.png ../OutQuint.gif; cd ..
cd InOutQuint; convert -delay 2 -loop 0 *.png ../InOutQuint.gif; cd ..
cd InSine; convert -delay 2 -loop 0 *.png ../InSine.gif; cd ..
cd OutSine; convert -delay 2 -loop 0 *.png ../OutSine.gif; cd ..
cd InOutSine; convert -delay 2 -loop 0 *.png ../InOutSine.gif; cd ..
cd InExpo; convert -delay 2 -loop 0 *.png ../InExpo.gif; cd ..
cd OutExpo; convert -delay 2 -loop 0 *.png ../OutExpo.gif; cd ..
cd InOutExpo; convert -delay 2 -loop 0 *.png ../InOutExpo.gif; cd ..
cd InCirc; convert -delay 2 -loop 0 *.png ../InCirc.gif; cd ..
cd OutCirc; convert -delay 2 -loop 0 *.png ../OutCirc.gif; cd ..
cd InOutCirc; convert -delay 2 -loop 0 *.png ../InOutCirc.gif; cd ..
cd InElastic; convert -delay 2 -loop 0 *.png ../InElastic.gif; cd ..
cd OutElastic; convert -delay 2 -loop 0 *.png ../OutElastic.gif; cd ..
cd InOutElastic; convert -delay 2 -loop 0 *.png ../InOutElastic.gif; cd ..
cd InBack; convert -delay 2 -loop 0 *.png ../InBack.gif; cd ..
cd OutBack; convert -delay 2 -loop 0 *.png ../OutBack.gif; cd ..
cd InOutBack; convert -delay 2 -loop 0 *.png ../InOutBack.gif; cd ..
cd InBounce; convert -delay 2 -loop 0 *.png ../InBounce.gif; cd ..
cd OutBounce; convert -delay 2 -loop 0 *.png ../OutBounce.gif; cd ..
cd InOutBounce; convert -delay 2 -loop 0 *.png ../InOutBounce.gif; cd ..